### ISSUE TITLE
Add good snow image

### ISSUE THREAD

**Issue by sasmlange** [intelweather/source#2]
There is only a not so good snow image right now.

**Comment by kostandrew** [comment]
Agreed

**Comment by sasmlange** [comment]
For the weather thumbnail

**Comment by kostandrew** [comment]
Added snowbanner1 and snowbanner2. Which one do you like better?

**Comment by sasmlange** [comment]
I like snowbanner1. It looks really nice. I was talking about the image for forecast.php, if you change the region to somewhere cold. I forget that there was two things about snow.

**Comment by kostandrew** [comment]
Ok I will photoshop an image of St. Anne to make it look like its snowing

**Comment by sasmlange** [comment]
Thanks

**Comment by kostandrew** [comment]
![Frame 22](https://github.com/intelweather/source/assets/151580428/2e4d7967-36ca-40c3-99bb-c9de72471701)
This ok? It looks kinda goofy 💀

**Comment by sasmlange** [comment]
It looks ok. Here is how it looks in the app:
![image](https://github.com/intelweather/source/assets/68520673/f6433895-495d-4519-a778-78d889d9bfa4)
The only issue is the snow does not really pop, but it is good enough.

**Comment by kostandrew** [comment]
I'll try to make the snow pop out more. One sec....

**Comment by sasankostelny** [comment]
![Uploading Frame 22(1).png…]()

**Comment by kostandrew** [comment]
![Frame 22(1)](https://github.com/intelweather/source/assets/151580428/9b23d8d3-2fb0-4892-9e77-83ea53af7d3b)

**Comment by sasmlange** [comment]
![image](https://github.com/intelweather/source/assets/68520673/1c35a6a4-1889-464d-a32d-db3fe9f84e22)

I think that looks better. What do you think?

**Comment by kostandrew** [comment]
Yeah it looks better

**Comment by sasmlange** [comment]
Great. Did you upload the image of should I?

**Comment by kostandrew** [comment]
Should we add the loader or nah? It says on the homepage that there wouldn't be a loader, but I don't know what else to put in place for the video while it is loading

**Comment by kostandrew** [comment]
Uh I'll upload it

**Comment by sasmlange** [comment]
I have been planing to remove the text about the loader as there already is a loader in the search.

**Comment by kostandrew** [comment]
Oh ok

**Comment by kostandrew** [comment]
Uh there's this weird thing with the loader where it only blocks the video
