### ISSUE TITLE
Gridpoints

### ISSUE THREAD

**Issue by kostandrew** [intelweather/source#5]
Hey Max are you able to find the gridpoints for New York, Los Angeles, Denver, Chicago, Houston, Philadelphia, San Antonio, San Diego, Phoenix, San Jose, Jacksonville, San Francisco, Seattle, Honolulu, Dallas, Atlanta, Miami, and Orlando or not. I'm kind of trash with the API stuff but I figured out the rest of the stuff except for the gridpoints. It'll be nice if you're able to find the gridpoints of these; if not, you can show me when we get back to school in a couple of days.

**Comment by sasmlange** [comment]
New York: https://api.weather.gov/gridpoints/OKX/33,35/forecast
Los Angeles: https://api.weather.gov/gridpoints/LOX/155,45/forecast
Denver: https://api.weather.gov/gridpoints/BOU/63,61/forecast
Chicago: https://api.weather.gov/gridpoints/LOT/76,73/forecast
Houston: https://api.weather.gov/gridpoints/HGX/65,96/forecast
Philadelphia: https://api.weather.gov/gridpoints/PHI/50,76/forecast
San Antonio: https://api.weather.gov/gridpoints/EWX/126,55/forecast
San Diego: https://api.weather.gov/gridpoints/SGX/57,14/forecast
Phoenix: https://api.weather.gov/gridpoints/PSR/159,58/forecast
San Jose: https://api.weather.gov/gridpoints/MTR/99,82/forecast
Jacksonville: https://api.weather.gov/gridpoints/JAX/66,65/forecast
San Francisco: https://api.weather.gov/gridpoints/MTR/85,105/forecast
Seattle: https://api.weather.gov/gridpoints/SEW/125,68/forecast
Honolulu: https://api.weather.gov/gridpoints/HFO/154,144/forecast
Dallas: https://api.weather.gov/gridpoints/FWD/89,104/forecast
Atlanta: https://api.weather.gov/gridpoints/FFC/51,87/forecast
Miami: https://api.weather.gov/gridpoints/MFL/110,51/forecast
Orlando: https://api.weather.gov/gridpoints/MLB/26,68/forecast

Hope this helps and happy Thanksgiving.

**Comment by kostandrew** [comment]
Ok thanks Max. I'll see you tomorrow at the beach! Happy Birthday and Happy (late) Thanksgiving!
